consumes:
- application/json
definitions:
  AuthPayload:
    description: Auth Payload is used to auth users.
    example:
      email: c
      password: Est ratione similique.
    properties:
      email:
        description: email of a user
        example: c
        minLength: 1
        type: string
      password:
        description: password of the user
        example: Est ratione similique.
        type: string
    required:
    - email
    - password
    title: AuthPayload
    type: object
  PostPayload:
    description: Post Payload is used to create posts.
    example:
      body: n0o
      published: false
      title: hb
    properties:
      body:
        description: body of a post
        example: n0o
        minLength: 1
        type: string
      published:
        description: is the post published
        example: false
        type: boolean
      title:
        description: name of a post
        example: hb
        minLength: 1
        type: string
    required:
    - title
    - body
    - published
    title: PostPayload
    type: object
  UserPayload:
    description: User Payload is used to create users.
    example:
      email: "4"
      name: c6m
      password: Eos voluptatem ut.
    properties:
      email:
        description: email of a user
        example: "4"
        minLength: 1
        type: string
      name:
        description: name of a user
        example: c6m
        minLength: 1
        type: string
      password:
        description: password of the user
        example: Eos voluptatem ut.
        type: string
    required:
    - name
    - email
    - password
    title: UserPayload
    type: object
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error'
    type: object
  post:
    description: post media type (default view)
    example:
      body: "6"
      id: 1.7503025e+18
      published: false
      title: "0"
    properties:
      body:
        description: body of a post
        example: "6"
        minLength: 1
        type: string
      id:
        description: Unique Post ID
        example: 1.7503025e+18
        format: int64
        type: integer
      published:
        description: is the post published
        example: false
        type: boolean
      title:
        description: name of a post
        example: "0"
        minLength: 1
        type: string
    required:
    - id
    - title
    - body
    - published
    title: 'Mediatype identifier: application/vnd.hixio.goa.post'
    type: object
  postCollection:
    description: postCollection is the media type for an array of post (default view)
    example:
    - body: "6"
      id: 1.7503025e+18
      published: false
      title: "0"
    - body: "6"
      id: 1.7503025e+18
      published: false
      title: "0"
    items:
      $ref: '#/definitions/post'
    title: 'Mediatype identifier: application/vnd.hixio.goa.post; type=collection'
    type: array
  user:
    description: user media type (default view)
    example:
      email: m
      id: 7.0499036e+18
      name: g8a
    properties:
      email:
        description: email of a user
        example: m
        minLength: 1
        type: string
      id:
        description: Unique Post ID
        example: 7.0499036e+18
        format: int64
        type: integer
      name:
        description: name of a user
        example: g8a
        minLength: 1
        type: string
    required:
    - id
    - name
    - email
    title: 'Mediatype identifier: application/vnd.hixio.goa.user'
    type: object
  userCollection:
    description: userCollection is the media type for an array of user (default view)
    example:
    - email: m
      id: 7.0499036e+18
      name: g8a
    items:
      $ref: '#/definitions/user'
    title: 'Mediatype identifier: application/vnd.hixio.goa.user; type=collection'
    type: array
host: 127.0.0.1:8080
info:
  description: Mike Hix's Blog Service
  version: ""
paths:
  /{filepath}:
    get:
      operationId: static#/*filepath
      parameters:
      - description: Relative file path
        in: path
        name: filepath
        required: true
        type: string
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/error'
      summary: Download static/
  /api/v1/auth:
    post:
      description: Creates a valid JWT
      operationId: auth#jwt
      parameters:
      - description: Auth Payload is used to auth users.
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/AuthPayload'
      responses:
        "204":
          description: No Content
          headers:
            Authorization:
              description: Generated JWT
              type: string
        "401":
          description: Unauthorized
      summary: jwt auth
      tags:
      - auth
  /api/v1/posts:
    get:
      description: lists all publisged posts
      operationId: post#list
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/postCollection'
      summary: list post
      tags:
      - post
    post:
      description: |-
        creates a post

        Required security scopes:
          * `api:access`
      operationId: post#create
      parameters:
      - description: Post Payload is used to create posts.
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/PostPayload'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/post'
        "500":
          description: Internal Server Error
      security:
      - jwt:
        - api:access
      summary: create post
      tags:
      - post
  /api/v1/posts/{id}:
    delete:
      description: |-
        deletes a post

        Required security scopes:
          * `api:access`
      operationId: post#delete
      parameters:
      - description: Unique Post ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - jwt:
        - api:access
      summary: delete post
      tags:
      - post
    get:
      description: shows a post
      operationId: post#show
      parameters:
      - description: Unique Post ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/post'
        "404":
          description: Not Found
      summary: show post
      tags:
      - post
  /api/v1/status:
    get:
      description: A basic status-check endpoint
      operationId: status#check
      responses:
        "200":
          description: OK
      summary: check status
      tags:
      - status
  /api/v1/users:
    get:
      description: |-
        lists all users

        Required security scopes:
          * `api:access`
      operationId: user#list
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/userCollection'
      security:
      - jwt:
        - api:access
      summary: list user
      tags:
      - user
    post:
      description: |-
        creates a user

        Required security scopes:
          * `api:access`
      operationId: user#create
      parameters:
      - description: User Payload is used to create users.
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UserPayload'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/user'
        "500":
          description: Internal Server Error
      security:
      - jwt:
        - api:access
      summary: create user
      tags:
      - user
  /api/v1/users/{id}:
    delete:
      description: |-
        deletes a user

        Required security scopes:
          * `api:access`
      operationId: user#delete
      parameters:
      - description: Unique Post ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - jwt:
        - api:access
      summary: delete user
      tags:
      - user
    get:
      description: |-
        shows a user

        Required security scopes:
          * `api:access`
      operationId: user#show
      parameters:
      - description: Unique Post ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user'
        "404":
          description: Not Found
      security:
      - jwt:
        - api:access
      summary: show user
      tags:
      - user
  /swagger-ui/{filepath}:
    get:
      operationId: swagger#/swagger-ui/*filepath
      parameters:
      - description: Relative file path
        in: path
        name: filepath
        required: true
        type: string
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/error'
      summary: Download swagger-ui/dist/
  /swagger.json:
    get:
      operationId: swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      summary: Download swagger/swagger.json
produces:
- application/json
responses:
  NoContent:
    description: No Content
  NotFound:
    description: Not Found
  OK:
    description: OK
    schema:
      $ref: '#/definitions/post'
  Unauthorized:
    description: Unauthorized
securityDefinitions:
  jwt:
    description: |2-


      **Security Scopes**:
        * `api:access`: API access
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
